import type { Metadata } from "next";
import { Poppins } from 'next/font/google';


export const metadata: Metadata = {
    title: 'Cambridge Secodary',
    description: 'Generated by Next.js',
  }

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});




export default function SecodaryLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
          <html lang="en" className="hydrated">
      <body className={poppins.className}>{children}</body>
    </html>

          
        </>
    )
}